server.port=8082

spring.datasource.url=mysql://root:fACsLBreGByfRzPAOfFmbczFiCyCvUVw@switchback.proxy.rlwy.net:51512/railway
spring.datasource.username=root
spring.datasource.password=fACsLBreGByfRzPAOfFmbczFiCyCvUVw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

cinevault.jwt.secret=CineVault$SecretKey#2024@HackathonProjectByTeam!SuperSecure256BitKey
cinevault.jwt.expiration-ms=86400000

cinevault.cors.allowed-origins=http://localhost:3000,http://localhost:5173

logging.level.com.cinevault=DEBUG